# Generated by Django 5.1.7 on 2025-04-25 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='video',
        ),
        migrations.AddField(
            model_name='technique',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Enter YouTube video URL', null=True),
        ),
    ]
