# Generated by Django 5.1.7 on 2025-04-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meditation', '0002_remove_technique_video_technique_youtube_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='google_meet_link',
            field=models.URLField(blank=True, help_text='Google Meet link for this session', max_length=255, null=True),
        ),
    ]
